In [1]:
import numpy as np
import cv2

In [3]:
img = cv2.imread('./images/flemingo.jpg') #in bgr formate

In [4]:
#img

In [5]:
#img.shape

In [6]:
b,g,r = cv2.split(img)

In [18]:
print(b)
print(g)
print(r)

[[188 189 189 ... 188 188 188]
 [188 189 189 ... 188 188 188]
 [188 189 189 ... 188 188 188]
 ...
 [167 167 167 ... 177 177 177]
 [173 173 174 ... 177 177 177]
 [177 177 178 ... 175 175 175]]
[[163 164 164 ... 163 163 163]
 [163 164 164 ... 163 163 163]
 [163 164 164 ... 163 163 163]
 ...
 [134 134 134 ... 144 144 144]
 [140 140 141 ... 144 144 144]
 [147 147 148 ... 145 145 145]]
[[119 120 120 ... 119 119 119]
 [119 120 120 ... 119 119 119]
 [119 120 120 ... 119 119 119]
 ...
 [ 88  88  88 ...  98  98  98]
 [ 94  94  95 ...  98  98  98]
 [100 100 101 ...  98  98  98]]


In [19]:
cv2.imshow('color',img)
cv2.imshow('blue',b)
cv2.imshow('red',r)
cv2.imshow('green',g)
cv2.waitKey(0)
cv2.destroyAllWindows()

# color convertor

In [24]:
img_rgb = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

In [25]:
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [ ]:
cv2.imshow('color_bgr',img)
cv2.imshow('color_rgb',img_rgb)
cv2.imshow('gray',gray)
cv2.waitKey(0)
cv2.destroyAllWindows()